### PR TITLE
Updates JSDOM to be compatible with node 4

### PR DESCRIPTION
**Pull request by warandpeace**

### CODE REVIEW

**Comment by TJkrusinski** [comment]
Hello, thanks for the PR, can you squash it into 1 commit?

**Comment by warandpeace** [comment]
@TJkrusinski: That was a thing I've never had to do before, but the answer is yes! Apparently I can!

Semi-related: The 'Articles' page linked is semi-deprecated on Clickhole and no longer paginates, so I'm rewriting bits of this in my library to function more like your buzzfeed-headlines library (ie. pull from multiple source pages)

I'll squash and sent it to you if you want, but if you're happy with the existing behaviour then I'll keep it in my fork

**Comment by TJkrusinski** [comment]
@warandpeace thanks! Yeah making the commit more concise for a PR is always welcome to maintainers (even though this project is super low key, it's good practice). That said, I'll merge this, then can you submit another with that extra functionality?

**Comment by warandpeace** [comment]
@TJkrusinski  Thanks for explaining, that's good to know! I'll send the new functionality over for you to review (as a single commit) shortly. Cheers!

**Pull request merged**
